foo/config/routes.rb
Rails.application.routes.draw do
  resources :doi_urls

  resources :dois

end

foo/app/models/doi.rb
class Doi < ActiveRecord::Base
end

foo/app/models/doi_url.rb
class DoiUrl < ActiveRecord::Base
  belongs_to :doi
end

foo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

foo/app/controllers/doi_urls_controller.rb
class DoiUrlsController < ApplicationController
  before_action :set_doi_url, only: [:show, :edit, :update, :destroy]

  # GET /doi_urls
  # GET /doi_urls.json
  def index
    @doi_urls = DoiUrl.all
  end

  # GET /doi_urls/1
  # GET /doi_urls/1.json
  def show
  end

  # GET /doi_urls/new
  def new
    @doi_url = DoiUrl.new
  end

  # GET /doi_urls/1/edit
  def edit
  end

  # POST /doi_urls
  # POST /doi_urls.json
  def create
    @doi_url = DoiUrl.new(doi_url_params)

    respond_to do |format|
      if @doi_url.save
        format.html { redirect_to @doi_url, notice: 'Doi url was successfully created.' }
        format.json { render :show, status: :created, location: @doi_url }
      else
        format.html { render :new }
        format.json { render json: @doi_url.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doi_urls/1
  # PATCH/PUT /doi_urls/1.json
  def update
    respond_to do |format|
      if @doi_url.update(doi_url_params)
        format.html { redirect_to @doi_url, notice: 'Doi url was successfully updated.' }
        format.json { render :show, status: :ok, location: @doi_url }
      else
        format.html { render :edit }
        format.json { render json: @doi_url.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doi_urls/1
  # DELETE /doi_urls/1.json
  def destroy
    @doi_url.destroy
    respond_to do |format|
      format.html { redirect_to doi_urls_url, notice: 'Doi url was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doi_url
      @doi_url = DoiUrl.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doi_url_params
      params.require(:doi_url).permit(:url, :name, :description, :doi_id)
    end
end

foo/app/controllers/dois_controller.rb
class DoisController < ApplicationController
  before_action :set_doi, only: [:show, :edit, :update, :destroy]

  # GET /dois
  # GET /dois.json
  def index
    @dois = Doi.all
  end

  # GET /dois/1
  # GET /dois/1.json
  def show
  end

  # GET /dois/new
  def new
    @doi = Doi.new
  end

  # GET /dois/1/edit
  def edit
  end

  # POST /dois
  # POST /dois.json
  def create
    @doi = Doi.new(doi_params)

    respond_to do |format|
      if @doi.save
        format.html { redirect_to @doi, notice: 'Doi was successfully created.' }
        format.json { render :show, status: :created, location: @doi }
      else
        format.html { render :new }
        format.json { render json: @doi.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dois/1
  # PATCH/PUT /dois/1.json
  def update
    respond_to do |format|
      if @doi.update(doi_params)
        format.html { redirect_to @doi, notice: 'Doi was successfully updated.' }
        format.json { render :show, status: :ok, location: @doi }
      else
        format.html { render :edit }
        format.json { render json: @doi.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dois/1
  # DELETE /dois/1.json
  def destroy
    @doi.destroy
    respond_to do |format|
      format.html { redirect_to dois_url, notice: 'Doi was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doi
      @doi = Doi.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doi_params
      params.require(:doi).permit(:doi_path)
    end
end

foo/app/helpers/application_helper.rb
module ApplicationHelper
end

foo/app/helpers/doi_urls_helper.rb
module DoiUrlsHelper
end

foo/app/helpers/dois_helper.rb
module DoisHelper
end

foo/app/views/doi_urls/_form.html.erb
<%= form_for(@doi_url) do |f| %>
  <% if @doi_url.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@doi_url.errors.count, "error") %> prohibited this doi_url from being saved:</h2>

      <ul>
      <% @doi_url.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :doi_id %><br>
    <%= f.text_field :doi_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

foo/app/views/doi_urls/edit.html.erb
<h1>Editing doi_url</h1>

<%= render 'form' %>

<%= link_to 'Show', @doi_url %> |
<%= link_to 'Back', doi_urls_path %>

foo/app/views/doi_urls/index.html.erb
<h1>Listing doi_urls</h1>

<table>
  <thead>
    <tr>
      <th>Url</th>
      <th>Name</th>
      <th>Description</th>
      <th>Doi</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doi_urls.each do |doi_url| %>
      <tr>
        <td><%= doi_url.url %></td>
        <td><%= doi_url.name %></td>
        <td><%= doi_url.description %></td>
        <td><%= doi_url.doi %></td>
        <td><%= link_to 'Show', doi_url %></td>
        <td><%= link_to 'Edit', edit_doi_url_path(doi_url) %></td>
        <td><%= link_to 'Destroy', doi_url, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Doi url', new_doi_url_path %>

foo/app/views/doi_urls/new.html.erb
<h1>New doi_url</h1>

<%= render 'form' %>

<%= link_to 'Back', doi_urls_path %>

foo/app/views/doi_urls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @doi_url.url %>
</p>

<p>
  <strong>Name:</strong>
  <%= @doi_url.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @doi_url.description %>
</p>

<p>
  <strong>Doi:</strong>
  <%= @doi_url.doi %>
</p>

<%= link_to 'Edit', edit_doi_url_path(@doi_url) %> |
<%= link_to 'Back', doi_urls_path %>

foo/app/views/dois/_form.html.erb
<%= form_for(@doi) do |f| %>
  <% if @doi.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@doi.errors.count, "error") %> prohibited this doi from being saved:</h2>

      <ul>
      <% @doi.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :doi_path %><br>
    <%= f.text_field :doi_path %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

foo/app/views/dois/edit.html.erb
<h1>Editing doi</h1>

<%= render 'form' %>

<%= link_to 'Show', @doi %> |
<%= link_to 'Back', dois_path %>

foo/app/views/dois/index.html.erb
<h1>Listing dois</h1>

<table>
  <thead>
    <tr>
      <th>Doi path</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dois.each do |doi| %>
      <tr>
        <td><%= doi.doi_path %></td>
        <td><%= link_to 'Show', doi %></td>
        <td><%= link_to 'Edit', edit_doi_path(doi) %></td>
        <td><%= link_to 'Destroy', doi, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Doi', new_doi_path %>

foo/app/views/dois/new.html.erb
<h1>New doi</h1>

<%= render 'form' %>

<%= link_to 'Back', dois_path %>

foo/app/views/dois/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Doi path:</strong>
  <%= @doi.doi_path %>
</p>

<%= link_to 'Edit', edit_doi_path(@doi) %> |
<%= link_to 'Back', dois_path %>