img.bs-broke/config/routes.rb
Rails.application.routes.draw do
  resources :images do
	resources :acls, :shallow => true
	resources :tags, :shallow => true
  end
  get '/images/:image_id/click' => 'images#click', as: 'image_click'
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  root to: 'images#index'
end

img.bs-broke/app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :user
  has_many :tags
  has_many :acls
  has_many :users, through: :acls
  accepts_nested_attributes_for :tags, :allow_destroy => true
  accepts_nested_attributes_for :acls, :allow_destroy => true
end

img.bs-broke/app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]
  respond_to :html, :xml, :json

  def index
    @images = Image.all
  if Rails.env.development? then
	@IMAGE_PATH = "images/"
  else
	@IMAGE_PATH = "public/images/"
  end

    respond_with(@images)
  end

  def show
    respond_with(@image)
  end

  def new
    @image = Image.new
    respond_with(@image)
  end

  def edit
  end

  def create
    @image = Image.new(image_params)
    @image.user = current_user

    @uploaded_io = params[:image][:uploaded_file]
    @image.filename = current_user.id.to_s + "_" + rand(10**5).to_s + "_" + @uploaded_io.original_filename 

    File.open(Rails.root.join('public', 'images', @image.filename), 'wb') do |file|
        file.write(@uploaded_io.read)
    end

    if @image.save
      redirect_to @image, notice: 'Image was successfully created.'
    else
      render :new
    end
  end

  def update
    @image.update(image_params)
    if(!params[:image][:uploaded_file].nil?) then
	    @uploaded_io = params[:image][:uploaded_file]
	    @image.filename = @uploaded_io.original_filename

	    File.open(Rails.root.join('public', 'images', @image.filename), 'wb') do |file|
        	file.write(@uploaded_io.read)
	    end
    end

    if @image.save
      redirect_to @image, notice: 'Image was successfully updated.'
    end
  end

  def destroy
    @image.destroy
    respond_with(@image)
  end

  def click
    @image = Image.find(params[:image_id])
  if Rails.env.development? then
	@IMAGE_PATH = "images/"
  else
	@IMAGE_PATH = "public/images/"
  end

    @jshide_code ="<script language=\"javascript\" type=\"text/javascript\">
function showHide(shID) {
   if (document.getElementById(shID)) {
      if (document.getElementById(shID+'-show').style.display != 'none') {
         document.getElementById(shID+'-show').style.display = 'none';
         document.getElementById(shID).style.display = 'block';
      }
      else {
         document.getElementById(shID+'-show').style.display = 'inline';
         document.getElementById(shID).style.display = 'none';
      }
   }
}
</script>"
     @some_style = "<style type=\"text/css\">
   /* This CSS is used for the Show/Hide functionality. */
   .more {
      display: none;
      border-top: 1px solid #666;
      border-bottom: 1px solid #666; }
   a.showLink, a.hideLink {
      text-decoration: none;
      color: #36f;
      padding-left: 8px;
      background: transparent url(down.gif) no-repeat left; }
   a.hideLink {
      background: transparent url(up.gif) no-repeat left; }
   a.showLink:hover, a.hideLink:hover {
      border-bottom: 1px dotted #36f; }
</style>"


  end

  private
    def set_image
      @image = Image.find(params[:id])
    end

    def image_params
      params.require(:image).permit(:filename, :private, :user_id, :original_filename)
    end
end

img.bs-broke/app/helpers/images_helper.rb
module ImagesHelper
end

img.bs-broke/app/views/images/_form.html.erb
<%= form_for(@image) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :filename %><br>
    <%= f.file_field :uploaded_file %>
  </div>
  <div class="field">
    <%= f.label :private %><br>
    <%= f.check_box :private %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

img.bs-broke/app/views/images/click.html.erb
<%= @jshide_code.html_safe %>
<%= @some_style.html_safe %>
<% if params[:commit] == "Update" then
	@image.tags_attributes = [ { :id => params[:update_tag_id], :tag_string => params[:update_tag] } ] 
	@image.save
end
%>
<% if params[:commit] == "Destroy" then
	@image.tags_attributes = [ { :id => params[:update_tag_id], '_destroy' => '1' } ]
	@image.save
end
%>
<% if params[:commit] == "Add" then
	@image.tags_attributes = [ { :tag_string => params[:update_tag] } ]
	@image.save
end
%>
<% if params[:commit] == "Grant" then
	@image.acls_attributes = [ { :user_id => params[:allow_user] } ]
	@image.save
end
%>
<% if params[:commit] == "Revoke" then
	params["remove"].each do |del| %>
		<%@image.acls.delete(del[1])
	end
end
%>
<%
@some_html = "<a href=\"#\" id=\"hidden0-show\" class=\"showLink\" onclick=\"showHide('hidden0');return false;\">add a tag</a>" 
@some_div = "<div id=\"hidden0\" class=\"more\">"
@more_html = "<a href=\"#\" id=\"hidden0-hidden\" class=\"hideLink\" onclick=\"showHide('hidden0');return false;\">Hide.</a>" 
%>



<center>
<%= image_tag(root_url + @IMAGE_PATH + @image.filename, width: '50%', alt: @image.filename) %>
<br><%= link_to 'Back', images_path %>
<br>Image owner: <%= @image.user.name %>
<% if @image.tags.count == 0 then %> 
	<%= "<br><br>No tags!".html_safe + @some_html.html_safe %> 
	<%= @some_div.html_safe %>
	<%= form_tag(image_click_path, method: "GET") do %>
		<%= "Tag: ".html_safe + text_field_tag(:update_tag) %>
	        <%= @more_html.html_safe %>
		<%= submit_tag "Add" %>
		<%= "</div>".html_safe %>
	<%end%>
   <% else %>
	<table>
	<tbody>
	<br>
	tags:
	<% @image.tags.each do |tag| %>
		<%= form_tag(image_click_path, method: "GET") do %>
			<tr>
			<td><%= tag.id %></td>
			<%-# if current_user.id == @image.user_id or @image.acls.exists?(current_user.id) then %>
			<% if current_user.id == @image.user_id then %>
				<td><%= text_field_tag(:update_tag, value = tag.tag_string) %></td>
				<td><%= submit_tag("Update") %></td>
				<%= hidden_field_tag 'update_tag_id', tag.id %>
				<td><%= submit_tag("Destroy") %></td>
			<% else %> 
				<td><%= tag.tag_string %></td>
			<%end%>
			</tr>
		<%end%>
	<% end %> 
	</tbody>
	</table>
        <%= @some_html.html_safe %>
        <%= @some_div.html_safe %>
        <%= form_tag(image_click_path, method: "GET") do %>
                <%= "Tag: ".html_safe + text_field_tag(:update_tag) %>
                <%= @more_html.html_safe %>
                <%= submit_tag "Add" %>
                <%= "</div>".html_safe %>
        <%end%>
<%end%>

<% if current_user.id == @image.user_id then %>
	<% @foos = User.all %>
	<%= form_tag(image_click_path, method: "GET") do %> 
		<%= select_tag('allow_user', options_from_collection_for_select(User.all, 'id', 'name_email')) %>
		<%= submit_tag("Grant") %>
	<%end%>

	<% if @image.acls.count != 0 then %>
		<table>
		<tbody>
		<%= form_tag(image_click_path, method: "GET") do %> 
			<% @image.acls.each_with_index do |acl, i| %>
				<% @user_name = User.find(acl.user_id).name %>
				<tr>
				<td><%= check_box_tag("remove[#{i}]", acl.id) %></td>
				<td><%= label_tag("acl", @user_name) %></td>
				</tr>
			<%end%>
			<td><%= submit_tag("Revoke") %></td>
		<%end%>
		</tbody>
		</table>
	<%end%>
<%end%>

</center>

img.bs-broke/app/views/images/edit.html.erb
<% if current_user.id == @image.user_id then %>
	<h1>Editing image</h1>
	<%= render 'form' %>
	<%= link_to 'Show', @image %> |
	<%= link_to 'Back', images_path %>
<% end %>

img.bs-broke/app/views/images/index.html.erb
<center><h1>Listing images</h1>

<table>
  <thead>
    <tr>
      <th>Filename</th>
      <th>Private</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  <% @images.each do |image| %>
	<% if !image.private? then %>
		<tr>
		<td><%= link_to(image_tag(root_url + @IMAGE_PATH + image.filename, size: "100x100", alt: image.filename), image_click_path(image)) %></td>
		<td><%= image.private %></td>
		<td><%= image.user.name %></td>
		<% if user_signed_in? and (current_user.id == image.user_id or image.acls.exists?(current_user.id)) then %>
			<td><%= link_to 'Show', image %></td>
			<td><%= link_to 'Edit', edit_image_path(image) %></td>
			<td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		<%end%>
	        </tr>
	<% else 
		if user_signed_in? then
			if image.user_id == current_user.id or image.acls.exists?(current_user.id) then %>
				<tr>
				<td><%= link_to(image_tag(root_url + @IMAGE_PATH + image.filename, size: "100x100", alt: image.filename), image_click_path(image)) %></td>
				<td><%= image.private %></td>
				<td><%= image.user.name %></td>
				<td><%= link_to 'Show', image %></td>
				<td><%= link_to 'Edit', edit_image_path(image) %></td>
				<td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
				</tr>
			<%end%>

		<%end%>
       <% end %>
    <% end %>
  </tbody>
</table>
</center>
<br>

<%= link_to 'New Image', new_image_path %>

img.bs-broke/app/views/images/new.html.erb
<h1>New image</h1>

<%= render 'form' %>

<%= link_to 'Back', images_path %>

img.bs-broke/app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Filename:</strong>
  <%= @image.filename %>
</p>

<p>
  <strong>Private:</strong>
  <%= @image.private %>
</p>

<p>
  <strong>User:</strong>
  <%= @image.user_id %>
</p>

<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>